Example 1:

In [2]:
import numpy as np

empty_array = np.empty(2, dtype=int)

zeros_array = np.zeros(5)

arange_array = np.arange(0, 10)

eye_matrix = np.eye(3)

randint_array = np.random.randint(1, 10, (3,3))

rand_array = np.random.rand(2, 3)

print("Empty:\n", empty_array)
print("Zeros:\n", zeros_array)
print("Arange:\n", arange_array)
print("Eye:\n", eye_matrix)
print("Randint:\n", randint_array)
print("Rand:\n", rand_array)

Empty:
 [3 3]
Zeros:
 [0. 0. 0. 0. 0.]
Arange:
 [0 1 2 3 4 5 6 7 8 9]
Eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Randint:
 [[4 7 9]
 [1 5 5]
 [1 1 6]]
Rand:
 [[0.19911897 0.51964303 0.89776902]
 [0.03317395 0.44856402 0.30601385]]


Example 2:

In [12]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Type:", arr.dtype)
print("Number of Dimensions:", arr.ndim)

Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Type: int64
Number of Dimensions: 1


Example 3:

In [13]:
import numpy as np

arr1d = np.array([1,2,3,4,5])
first_element = arr1d[0]
print("The first element of arr1d:", first_element)
last_element = arr1d[-1]
print("The first element of arr1d:", last_element)

The first element of arr1d: 1
The first element of arr1d: 5


Example 4:

In [14]:
import numpy as np

arr2d = np.array([[1,2,3], [4,5,6]])
print(arr2d)
element_1_2 = arr2d[0,1]
print(element_1_2)

[[1 2 3]
 [4 5 6]]
2


Example 5:

In [15]:
import numpy as np

arr1d = np.array([1,2,3,4,5])
slide_arr1 = arr1d[1:4]
print("arr1d:", arr1d)
print("Slicing arr1d from 1 to 3:", slide_arr1)

arr1d: [1 2 3 4 5]
Slicing arr1d from 1 to 3: [2 3 4]


Example 6:

In [16]:
import numpy as np

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
slide_arr2d = arr2d[1:3, 1:]
print("arr2d:\n", arr2d)
print("Slicing arr2d from row 2 to row 3 and col 2 to col end:\n", slide_arr2d)

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing arr2d from row 2 to row 3 and col 2 to col end:
 [[5 6]
 [8 9]]


Example 7:

In [17]:
import numpy as np

original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

new_array = original_array.transpose()
print(new_array)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Example 8:

In [18]:
import numpy as np

original_array = np.array([[0,1],[2,3],[4,5]])
new_array = np.reshape(original_array, (2,3))
print(new_array)

[[0 1 2]
 [3 4 5]]


Example 9:

In [19]:
import numpy as np

arr_2D = np.array([[1,2,3],[4,5,6]])

new_arr_2D = np.reshape(arr_2D, (3,2))
arr_1D = np.reshape(arr_2D, shape=(6,))
print("Array 2D:\n", arr_2D, arr_2D.shape)
print("New array 2D:\n", new_arr_2D, new_arr_2D.shape)
print("Array 1D:\n", arr_1D, arr_1D.shape)

Array 2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
New array 2D:
 [[1 2]
 [3 4]
 [5 6]] (3, 2)
Array 1D:
 [1 2 3 4 5 6] (6,)


Example 10:

In [20]:
import numpy as np

original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

original_array.resize(3,4)
print(original_array)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]]


Example 11:

In [22]:
import numpy as np

original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
new_array1 = np.insert(original_array,0,[10,10,10],axis=0)
new_array2 = np.insert(original_array,3,[10,10,10],axis=0)
new_array3 = np.insert(original_array,0,[10,10,10],axis=1)
new_array4 = np.insert(original_array,3,[10,10,10],axis=1)

print("Arr1:\n", new_array1)
print("Arr2:\n", new_array2)
print("Arr3:\n", new_array3)
print("Arr4:\n", new_array4)

Arr1:
 [[10 10 10]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Arr2:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 10 10]]
Arr3:
 [[10  1  2  3]
 [10  4  5  6]
 [10  7  8  9]]
Arr4:
 [[ 1  2  3 10]
 [ 4  5  6 10]
 [ 7  8  9 10]]


Example 12:

In [23]:
import numpy as np

original_array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
original_array2 = np.array([[10,20,30],[40,50,60],[70,80,90]])

new_array1 = np.append(original_array1,original_array2,axis=1)
new_array2 = np.append(original_array1,original_array2,axis=0)

print("New arr 1:\n", new_array1)
print("New arr 2:\n", new_array2)

New arr 1:
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
New arr 2:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


Example 13:

In [24]:
import numpy as np

original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

new_array1 = np.delete(original_array,0,axis=0)
new_array2 = np.delete(original_array,0,axis=1)
new_array3 = np.delete(original_array,2,axis=0)
new_array4 = np.delete(original_array,2,axis=1)

print("Arr1:\n", new_array1)
print("Arr2:\n", new_array2)
print("Arr3:\n", new_array3)
print("Arr4:\n", new_array4)

Arr1:
 [[4 5 6]
 [7 8 9]]
Arr2:
 [[2 3]
 [5 6]
 [8 9]]
Arr3:
 [[1 2 3]
 [4 5 6]]
Arr4:
 [[1 2]
 [4 5]
 [7 8]]


Example 14:

In [31]:
import numpy as np

# a = np.array([[0,1,3],[5,7,9],[7,8,9]]) #error
a = np.array([[0,1,3],[5,7,9]])
b = np.array([[0,2,4],[6,8,10]])

con_ab = np.concatenate((a,b), axis=1)
hst_ab = np.hstack((a,b))
vst_ab = np.vstack((a,b))

print("Array a:\n", a)
print("Array b:\n", b)
print("Concatenate:\n", con_ab)
print("Hor stack:\n", hst_ab)
print("Ver stack:\n", vst_ab)

Array a:
 [[0 1 3]
 [5 7 9]]
Array b:
 [[ 0  2  4]
 [ 6  8 10]]
Concatenate:
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
Hor stack:
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
Ver stack:
 [[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


Example 15:

In [32]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.hstack((arr_1, arr_2))
print("arr 1:\n", arr_1)
print("arr 2:\n", arr_2)
print("Result arr:\n", arr_3)

arr 1:
 [1 2 3]
arr 2:
 [4 5 6]
Result arr:
 [1 2 3 4 5 6]


Example 16:

In [33]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.vstack((arr_1, arr_2))
print("arr 1:\n", arr_1)
print("arr 2:\n", arr_2)
print("Result arr:\n", arr_3)

arr 1:
 [1 2 3]
arr 2:
 [4 5 6]
Result arr:
 [[1 2 3]
 [4 5 6]]


Example 17:

In [35]:
import numpy as np

arr_1 = np.array([[1,2,3],[4,5,6]])
arr_2 = np.array([[7,8,9],[10,11,12]])
arr_3 = np.concatenate((arr_1, arr_2),axis=0)
arr_4 = np.concatenate((arr_1, arr_2),axis=1)

print("arr 1:\n", arr_1)
print("arr 2:\n", arr_2)
print("Result (axis=0):\n", arr_3)
print("Result (axis=1):\n", arr_4)

arr 1:
 [[1 2 3]
 [4 5 6]]
arr 2:
 [[ 7  8  9]
 [10 11 12]]
Result (axis=0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Result (axis=1):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Example 18:

In [37]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = arr_1[np.newaxis, :]
arr_3 = arr_2[np.newaxis, :, np.newaxis, :, np.newaxis]
print("arr 1:\n", arr_1, arr_1.shape)
print("arr 2:\n", arr_2, arr_2.shape)
print("arr 3:\n", arr_3, arr_3.shape)

arr 1:
 [1 2 3] (3,)
arr 2:
 [[1 2 3]] (1, 3)
arr 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


Example 19:

In [39]:
import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.expand_dims(arr_1,axis=0)
arr_3 = np.expand_dims(arr_2,axis=(0,2,4))

print("arr 1:\n", arr_1, arr_1.shape)
print("arr 2:\n", arr_2, arr_2.shape)
print("arr 3:\n", arr_3, arr_3.shape)

arr 1:
 [1 2 3] (3,)
arr 2:
 [[1 2 3]] (1, 3)
arr 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


Example 20:

In [40]:
import numpy as np

arr2d = np.array([[1,7,3],[10,8,6],[5,15,9]])
print("Original array:\n", arr2d)
sort_in_row = np.sort(arr2d,axis=1)
sort_in_col = np.sort(arr2d,axis=0)
print("Result by row:\n",sort_in_row)
print("Result by col:\n",sort_in_col)

Original array:
 [[ 1  7  3]
 [10  8  6]
 [ 5 15  9]]
Result by row:
 [[ 1  3  7]
 [ 6  8 10]
 [ 5  9 15]]
Result by col:
 [[ 1  7  3]
 [ 5  8  6]
 [10 15  9]]


Example 21:

In [4]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,11])

print("a =\n", a)
print("b =\n", b)
print("Add:\n", np.add(a,b))
print("Sub:\n", np.subtract(a,b))
print("Mul:\n", np.multiply(a,b))
print("Div:\n", np.divide(a,b))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 11]
Add:
 [[10  8 12]
 [13 12 16]
 [16  9 19]]
Sub:
 [[-10  -2 -10]
 [ -7   2  -6]
 [ -4  -1  -3]]
Mul:
 [[ 0 15 11]
 [30 35 55]
 [60 20 88]]
Div:
 [[0.         0.6        0.09090909]
 [0.3        1.4        0.45454545]
 [0.6        0.8        0.72727273]]


Example 23:

In [11]:
import numpy as np

a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])

print("a =\n", a)
print("b =\n", b)
print("Remainder:\n", np.remainder(a,b))
print("Power:\n", np.power(a,b))
print("Mod:\n", np.mod(a,b))
print("Reciprocal:\n", np.reciprocal(a))

a = np.array([7.0,3,4,5,1])
print("Reciprocal:\n", np.reciprocal(a))

a =
 [7 3 4 5 1]
b =
 [3 4 5 6 7]
Remainder:
 [1 3 4 5 1]
Power:
 [  343    81  1024 15625     1]
Mod:
 [1 3 4 5 1]
Reciprocal:
 [0 0 0 0 1]
Reciprocal:
 [0.14285714 0.33333333 0.25       0.2        1.        ]


Example 24:

In [13]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print(np.sum(a))
print(np.sum(b))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]
37
25
[ 9 14 14]
[ 4 15 18]


Example 25:

In [14]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print("Sum_a =", np.sum(a))
print("Sum_b =", np.sum(b))
print("Sum_a_axis_0 =", np.sum(a, axis=0))
print("Sum_a_axis_1 =", np.sum(a, axis=1))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]
Sum_a = 37
Sum_b = 25
Sum_a_axis_0 = [ 9 14 14]
Sum_a_axis_1 = [ 4 15 18]


Example 26:

In [15]:
import numpy as np

arr = np.array([1,2,3,4,5])
max_value = np.max(arr)
print("Largest value :", max_value)
min_value = np.min(arr)
print("Smallest value :", min_value)

Largest value : 5
Smallest value : 1


Example 27:

In [17]:
import numpy as np

arr2d = np.array([[1,2,3],[4,5,6]])
max_value_row = np.max(arr2d, axis=1)
max_value_col = np.max(arr2d, axis=0)
print("Maximum value in row:", max_value_row)
print("Maximum value in col:", max_value_col)

min_value_row = np.min(arr2d, axis=1)
min_value_col = np.min(arr2d, axis=0)
print("Minimum value in row:", min_value_row)
print("Minimum value in col:", min_value_col)

Maximum value in row: [3 6]
Maximum value in col: [4 5 6]
Minimum value in row: [1 4]
Minimum value in col: [1 2 3]


Example 28:

In [19]:
import numpy as np

arr2d = np.array([[1,2,3],[4,5,6]])
max_value_row = np.max(arr2d, axis=1)
max_index_row = np.argmax(arr2d, axis=1)
print("Maximum value in row:", max_value_row)
print("Index:", max_index_row)

max_value_col = np.max(arr2d, axis=0)
max_index_col = np.argmax(arr2d, axis=0)
print("Maximum value in col:", max_value_col)
print("Index:", max_index_col)

Maximum value in row: [3 6]
Index: [2 2]
Maximum value in col: [4 5 6]
Index: [1 1 1]


Example 29:

In [22]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print()
print(np.median(a))
print(np.median(b))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]

4.0
10.0
[3. 4. 5.]
[1. 5. 6.]


Example 30:

In [26]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print("Median value in row:", np.median(a, axis=1))
print("Median value in col:", np.median(a, axis=0))
print("Median array A:", np.median(a))
print("Median array B:", np.median(b))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]
Median value in row: [1. 5. 6.]
Median value in col: [3. 4. 5.]
Median array A: 4.0
Median array B: 10.0


Example 31:

In [27]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print()
print(np.mean(a))
print(np.mean(b))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]

4.111111111111111
8.333333333333334
[3.         4.66666667 4.66666667]
[1.33333333 5.         6.        ]


Example 32:

In [28]:
import numpy as np

a = np.array([[0,3,1],[3,7,5],[6,4,8]])
b = np.array([10,5,10])

print("a =\n", a)
print("b =\n", b)
print("Mean_a =", np.mean(a))
print("Mean_b =", np.mean(b))
print("Mean_a_axis_0 =", np.mean(a, axis=0))
print("Mean_a_axis_1 =", np.mean(a, axis=1))

a =
 [[0 3 1]
 [3 7 5]
 [6 4 8]]
b =
 [10  5 10]
Mean_a = 4.111111111111111
Mean_b = 8.333333333333334
Mean_a_axis_0 = [3.         4.66666667 4.66666667]
Mean_a_axis_1 = [1.33333333 5.         6.        ]


Example 33:

In [29]:
import numpy as np

a = np.array([[4,12,0,4],[6,11,8,4],[18,14,13,7]])

print("a =\n", a)
print()
print(np.std(a, axis=0))
print(np.std(a, axis=1))
print(np.var(a, axis=0))
print(np.var(a, axis=1))

a =
 [[ 4 12  0  4]
 [ 6 11  8  4]
 [18 14 13  7]]

[6.18241233 1.24721913 5.35412613 1.41421356]
[4.35889894 2.58602011 3.93700394]
[38.22222222  1.55555556 28.66666667  2.        ]
[19.      6.6875 15.5   ]


Example 34:

In [31]:
import numpy as np

a = np.array([[4,12,0,4],[6,11,8,4],[18,14,13,7]])

print("a =\n", a)
print()
print("Standard Deviation_a_axis_0 =", np.std(a, axis=0))
print("Standard Deviation_a_axis_1 =", np.std(a, axis=1))
print("Variance_a_axis_0 =", np.var(a, axis=0))
print("Variance_a_axis_1 =", np.var(a, axis=1))

a =
 [[ 4 12  0  4]
 [ 6 11  8  4]
 [18 14 13  7]]

Standard Deviation_a_axis_0 = [6.18241233 1.24721913 5.35412613 1.41421356]
Standard Deviation_a_axis_1 = [4.35889894 2.58602011 3.93700394]
Variance_a_axis_0 = [38.22222222  1.55555556 28.66666667  2.        ]
Variance_a_axis_1 = [19.      6.6875 15.5   ]


Example 35:

In [32]:
import numpy as np

arr = np.array([1,2,3,4,5])
result = np.where(arr>2)
print("Posotion of elements freater than 2:", result)
print("The value of the elements at the found position", arr[result])

Posotion of elements freater than 2: (array([2, 3, 4]),)
The value of the elements at the found position [3 4 5]


Example 36:

In [33]:
import numpy as np

a = np.array([[1,0],[0,1]])
b = np.array([[4,1],[2,2]])

print("Dot_Result =\n", np.dot(a,b))
print("Vdot_Result =\n", np.vdot(a,b))
print("Inner_Result =\n", np.inner(a,b))
print("Outer_Result =\n", np.outer(a,b))

Dot_Result =
 [[4 1]
 [2 2]]
Vdot_Result =
 6
Inner_Result =
 [[4 2]
 [1 2]]
Outer_Result =
 [[4 1 2 2]
 [0 0 0 0]
 [0 0 0 0]
 [4 1 2 2]]


Example 37:

In [34]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("arr_1 =\n", a)
print("arr_2 =\n", b)
result = np.matmul(a,b)
print("Result =\n", result)

arr_1 =
 [[1 2]
 [3 4]]
arr_2 =
 [[5 6]
 [7 8]]
Result =
 [[19 22]
 [43 50]]


Example 38:

In [38]:
import math

def Euclicdean_distance(point1, point2):
    return math.sqrt((point1[0]-point2[0])**2 + (point1[1]-point2[1])**2)
point1 = (1,2)
point2 = (4,6)
distance = Euclicdean_distance(point1, point2)
print("Euclicdean distance:",distance)

import numpy as np

def Euclicdean_distance_np(point1, point2):
    return np.linalg.norm(np.array(point1)-np.array(point2))
point1 = (1,2)
point2 = (4,6)
distance = Euclicdean_distance_np(point1, point2)
print("Euclicdean distance (NumPy):",distance)

Euclicdean distance: 5.0
Euclicdean distance (NumPy): 5.0


Example 39:

In [39]:
def manhattan_distance(point1, point2):
    return sum(abs(a-b) for a,b in zip(point1, point2))
point1 = (1,2)
point2 = (4,6)
distance = manhattan_distance(point1, point2)
print("Manhattan distance:",distance)

import numpy as np
def manhattan_distance_np(point1, point2):
    return np.sum(np.abs(np.array(point1) - np.array(point2)))
point1 = (1,2)
point2 = (4,6)
distance = manhattan_distance_np(point1, point2)
print("Manhattan distance (NumPy):",distance)

Manhattan distance: 7
Manhattan distance (NumPy): 7


Example 40:

In [47]:
import numpy as np
import numpy.matlib as ml

mat_e = ml.empty((3,2), dtype=int)
mat_zeros = ml.zeros((5,3))
mat_ones = ml.ones((4,3))
mat_eye = ml.eye(3,5)
mat_iden = ml.identity(5)
mat_e_r = ml.empty((3,2))

print(mat_e)
print()
print(mat_zeros)
print()
print(mat_ones)
print()
print(mat_eye)
print()
print(mat_iden)
print()
print(mat_e_r)

[[1 0]
 [0 0]
 [0 0]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[5.e-324 0.e+000]
 [0.e+000 0.e+000]
 [0.e+000 0.e+000]]


Example 41:

In [48]:
import numpy as np

a = np.array([1,2,3,4,5])
np.save("source/chap_5/out.npy",a)
b = np.load("source/chap_5/out.npy")
print(b)

[1 2 3 4 5]


Example 42:

In [49]:
import numpy as np

a = np.array([1,2,3,4,5])
np.savetxt("source/chap_5/out.txt",a)
b = np.loadtxt("source/chap_5/out.txt")
print(b)

[1. 2. 3. 4. 5.]
